PBName: "&4&lPower Ball"
Items:
  Diamonds1:
    Item: diamond
    Amount: 1
    Chance: 0.01
  Diamonds2:
    Item: diamond
    Name: "This is a diamond"
    Lore:
    - "Diamond lore ohhhhhhh :o"
    Enchantments:
    - damage_all,5
    Amount: 3
    Chance: 0.01
  Potion1:
    Item: potion
    Amount: 1
    Effects:
    - heal
    Chance: 1.0
