name: PowerBall
main: me.endureblackout.PowerBall.PowerBall
version: 1.0
api-version: 1.20
description: Alternative to crates.
depend: [VanityGear]
author: [EndureBlackout]
commands:
  pb:
    description: Main PowerBall command.
